services:
  mysql:
    image: mysql
    container_name: patcom_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./bin/data:/var/lib/mysql
      - ./db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql

